version: "3.1"

services:
  db:
    image: mongo
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db

  app:
    build: .
    restart: on-failure
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
    depends_on:
      - db

  nginx:
    build: ./services/nginx
    restart: on-failure
    ports:
      - 8080:80
    depends_on:
      - app
